- name: Install USB-Support
  community.general.opkg:
    name: "{{ item }}"
    state: present
  loop:
    - usbutils
    - kmod-usb-core
    - kmod-usb-storage
    - block-mount
    - kmod-fs-{{ openwrt_pxe_usb_filesystem }}

- name: Check if anonymous mount is enabled
  ansible.builtin.command: uci get fstab.@global[0].anon_mount
  register: anon_mount
  changed_when: false

- name: Enable anonymous mount
  ansible.builtin.command: uci set fstab.@global[0].anon_mount=1
  when: anon_mount.stdout != "1"
  changed_when: true
  notify:
    - Commit fstab
    - Boot fstab

- name: Check if USB drive mount is enabled
  ansible.builtin.command: uci get fstab.@mount[0].enabled
  register: usb_mount
  changed_when: false

- name: Enable USB drive mount
  ansible.builtin.command: uci set fstab.@mount[0].enabled=1
  when: usb_mount.stdout != "1"
  changed_when: true
  notify:
    - Commit fstab
    - Boot fstab

- name: Detect if target is correct
  ansible.builtin.command: uci get fstab.@mount[0].target
  register: target
  changed_when: false

- name: Set target
  ansible.builtin.command: uci set fstab.@mount[0].target={{ openwrt_pxe_mountpoint }}
  when: target.stdout != openwrt_pxe_usb_mountpoint
  changed_when: true
  notify:
    - Commit fstab
    - Boot fstab
