- name: Commit fstab
  ansible.builtin.command: uci commit fstab
  changed_when: true

- name: Boot fstab
  ansible.builtin.command: service fstab boot
  changed_when: true

- name: Commit dhcp
  ansible.builtin.command: uci commit dhcp
  changed_when: true

- name: Restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
